import type { AdminSettingsDict } from "../types";

export const adminSettingsSr = {
  title: "Podešavanja", subtitle: "Centralna pravila, cene i proverljiva stanja integracija.",
  general: "Opšte", subscriptions: "Pretplate", payments: "Plaćanja", communication: "Komunikacija", pricing: "Cene i popusti", referral: "Referral",
  timezone: "Vremenska zona", currency: "Osnovna valuta", policyVersion: "Poslovna pravila ADMIN-V1",
  readOnly: "Zaključano pravilo", monthlyWarning: "Mesečni warning", annualWarning: "Godišnji warning", monthlyGrace: "Mesečni grace", annualGrace: "Godišnji grace", days: "dana", lifecycleNote: "Upozorenje pre isteka nije status pretplate. Posle grace perioda kanonski lifecycle može preći u suspendovano stanje.",
  bankTransfer: "Uplata na račun", supported: "Podržano", card: "Platna kartica", unavailable: "Nedostupno", cash: "Gotovina", notConfigured: "Nije podešeno", paymentNote: "Interni i other načini nisu javno ponuđeni klijentu bez eksplicitnog pravila.",
  foundation: "Provider-neutral foundation", configured: "Konfiguracija", inbound: "Inbound, slanje i odgovor", needsConfiguration: "Potrebna konfiguracija", notConnected: "Nije povezano", communicationNote: "Mailbox, OAuth, nalog i folderi nisu potvrđeni. ADMIN-09C nije deo ove stranice.",
  premiumReference: "Premium referentna cena", temporary: "Privremena referentna cena", monthly: "mesečno", futurePrice: "Zakaži buduću cenu", amount: "Iznos u RSD", validFrom: "Važi od", validUntil: "Važi do", reason: "Razlog", reasonPlaceholder: "Zašto se referentna cena menja?", save: "Sačuvaj izmene", cancel: "Otkaži", unsaved: "Nesačuvane izmene", saved: "Izmene su sačuvane.", priceNote: "Promena služi samo budućim ponudama i obračunima. Ne menja postojeće dogovore, period snapshot-e, uplate, alokacije ni ledger.", agreementNote: "Founders, Enterprise, individualne cene i Prijatelj postoje samo kao eksplicitni ugovori po nalogu i targetu; nema podrazumevanih cena ili popusta.",
  referralNote: "Uslovi nisu podešeni. Referral se kvalifikuje tek prvom pozitivnom settled uplatom preporučenog naloga; stornirana uplata ne ostavlja nagradu.",
  agreements: "Dogovorene cene", agreementAccount: "Nalog", agreementTarget: "Pretplata", agreementKind: "Vrsta dogovora", agreementReference: "Referentna cena", agreementPrice: "Dogovorena cena", agreementCreate: "Dodaj dogovor", agreementEmpty: "Nema postojećih dogovora.", referralRegister: "Registruj referral", referrer: "Preporučilac", referred: "Preporučeni nalog", referralEmpty: "Nema registrovanih referral stavki.", chooseAccount: "Izaberi nalog", chooseTarget: "Izaberi pretplatu", founders: "Founders", enterprise: "Enterprise", individual: "Individualna", standard: "Standardna", pending: "Na čekanju", qualified: "Kvalifikovan", rewarded: "Nagrađen", cancelled: "Otkazan",
  friendWaiver: "Prijatelj waiver", friendTag: "Prijatelj oznaka", friendWaiverCreate: "Primeni eksplicitan waiver", friendWaiverNote: "Oslobađanje važi samo za izabranu pretplatu i period; sama oznaka nema finansijski efekat.",
  leaveDraftTitle: "Nesačuvane izmene", leaveDraftBody: "Ako nastavite, izmene na ovoj stranici biće odbačene.", leaveDraftStay: "Ostani", leaveDraftLeave: "Nastavi bez čuvanja",
  loading: "Učitavanje podešavanja", error: "Podešavanja nisu učitana.", invalidAmount: "Unesi ceo nenegativan iznos.", invalidDate: "Datum početka mora biti u budućnosti.", invalidReason: "Razlog je obavezan.", conflict: "Neko je već izmenio pravila. Osveži prikaz i proveri podatke.", saveFailed: "Izmena nije sačuvana. Pokušaj ponovo.",
  annual: "godišnje", serviceSubscription: "Servis", from: "Od", until: "do", lifetime: "bez isteka", foundersNote: "Founders mora imati eksplicitno trajanje: prazno Važi do znači doživotni ugovor.", chooseFriend: "Izaberi nalog sa Prijatelj oznakom", invalidAgreement: "Popuni nalog, pretplatu, celobrojne cene, budući datum i razlog.", agreementSaved: "Dogovorena cena je sačuvana.", invalidWaiver: "Izaberi Prijatelj nalog, pretplatu, budući datum i razlog.", waiverSaved: "Ciljani Prijatelj waiver je sačuvan.", invalidReferral: "Izaberi dva različita naloga i navedi razlog.", referralSaved: "Referral je registrovan.", rewardAgreement: "Eksplicitni uslovi nagrade", rewardNote: "Nema podrazumevane nagrade. Samo kvalifikovan referral može dobiti budući, ciljani uslov.", chooseReferral: "Izaberi kvalifikovan referral", rewardType: "Vrsta nagrade", percentage: "Procenat", fixedAmount: "Fiksni iznos u RSD", basisPoints: "Bazni poeni (100 = 1%)", invalidReward: "Izaberi kvalifikovan referral i target, navedi validan budući uslov i razlog.", rewardCreate: "Dodaj uslov nagrade", rewardSaved: "Uslov referral nagrade je sačuvan.", previewBadge: "Demo prikaz · neprodukcijski podaci", previewDescription: "Testne cene i referral stavke služe samo za proveru interakcije; nisu poslovna odluka niti se upisuju u Convex.",
} as const satisfies AdminSettingsDict;
