import type { ComponentType, SVGProps } from "react";
import {
  siFacebook,
  siInstagram,
  siTelegram,
  siTiktok,
  siViber,
  siWhatsapp,
  siYoutube,
  type SimpleIcon,
} from "simple-icons";
import {
  BookOpen,
  CalendarDays,
  Camera,
  Clock,
  Coffee,
  Contact,
  CreditCard,
  Gift,
  Globe2,
  Heart,
  Home,
  Link as LinkIcon,
  type LucideIcon,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Music,
  Navigation,
  Percent,
  Phone,
  QrCode,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Tag,
  Ticket,
  Truck,
  User,
  Utensils,
} from "lucide-react";

// Lucide
import {
  LuBanknote,
  LuBeer,
  LuBell,
  LuBookmark,
  LuBuilding,
  LuCake,
  LuCalendar,
  LuCamera,
  LuChefHat,
  LuCircleHelp,
  LuClock,
  LuCoffee,
  LuCompass,
  LuCookie,
  LuCreditCard,
  LuCroissant,
  LuCupSoda,
  LuFacebook,
  LuFlame,
  LuGift,
  LuGithub,
  LuGlobe,
  LuHeart,
  LuHouse,
  LuIceCreamBowl,
  LuInfo,
  LuInstagram,
  LuLink,
  LuLinkedin,
  LuMail,
  LuMapPin,
  LuMessageCircle,
  LuMusic,
  LuNavigation,
  LuPackage,
  LuPercent,
  LuPhone,
  LuPizza,
  LuQrCode,
  LuReceipt,
  LuSalad,
  LuShare2,
  LuShieldCheck,
  LuShoppingBag,
  LuShoppingCart,
  LuSoup,
  LuSparkles,
  LuStar,
  LuStore,
  LuTag,
  LuThumbsUp,
  LuTicket,
  LuTruck,
  LuTwitter,
  LuUser,
  LuUsers,
  LuUtensils,
  LuVideo,
  LuWine,
  LuYoutube,
  LuZap,
} from "react-icons/lu";

// Font Awesome 6
import {
  FaBagShopping,
  FaBeerMugEmpty,
  FaBell,
  FaBolt,
  FaBookOpen,
  FaBookmark,
  FaBoxOpen,
  FaBuilding as FaBuilding6,
  FaBurger,
  FaCakeCandles,
  FaCalendarDays as FaCalendarDays6,
  FaCamera as FaCamera6,
  FaCartShopping,
  FaCircleInfo,
  FaCircleQuestion,
  FaClock as FaClock6,
  FaCoins,
  FaCommentDots,
  FaCompass as FaCompass6,
  FaCreditCard as FaCreditCard6,
  FaDiscord,
  FaEnvelope,
  FaFacebookF,
  FaFire,
  FaFish,
  FaGift as FaGift6,
  FaGlobe as FaGlobe6,
  FaGoogle,
  FaHeart as FaHeart6,
  FaHouse as FaHouse6,
  FaIceCream as FaIceCream6,
  FaInstagram as FaInstagram6,
  FaLink as FaLink6,
  FaLinkedinIn,
  FaLocationArrow,
  FaLocationDot,
  FaMugHot,
  FaMusic as FaMusic6,
  FaPercent as FaPercent6,
  FaPhone as FaPhone6,
  FaPinterestP,
  FaPizzaSlice,
  FaQrcode as FaQrcode6,
  FaReceipt as FaReceipt6,
  FaShareNodes,
  FaShieldHalved,
  FaShop,
  FaSnapchat,
  FaSpotify,
  FaStar as FaStar6,
  FaTag as FaTag6,
  FaTelegram as FaTelegram6,
  FaThumbsUp as FaThumbsUp6,
  FaTicket as FaTicket6,
  FaTiktok as FaTiktok6,
  FaTruck as FaTruck6,
  FaUser as FaUser6,
  FaUsers as FaUsers6,
  FaUtensils as FaUtensils6,
  FaVideo as FaVideo6,
  FaViber as FaViber6,
  FaWandMagicSparkles,
  FaWhatsapp as FaWhatsapp6,
  FaWineGlass,
  FaXTwitter,
  FaYelp,
  FaYoutube as FaYoutube6,
} from "react-icons/fa6";

// Tabler
import {
  TbBeer,
  TbBell as TbBellIcon,
  TbBolt as TbBoltIcon,
  TbBook as TbBookIcon,
  TbBookmark as TbBookmarkIcon,
  TbBrandDiscord,
  TbBrandFacebook,
  TbBrandGoogle,
  TbBrandInstagram,
  TbBrandLinkedin,
  TbBrandPinterest,
  TbBrandSnapchat,
  TbBrandSpotify,
  TbBrandTelegram,
  TbBrandTiktok,
  TbBrandTripadvisor,
  TbBrandWhatsapp,
  TbBrandX,
  TbBrandYoutube,
  TbBuilding as TbBuildingIcon,
  TbBuildingStore,
  TbBurger as TbBurgerIcon,
  TbCake as TbCakeIcon,
  TbCalendar as TbCalendarIcon,
  TbCamera as TbCameraIcon,
  TbClock as TbClockIcon,
  TbCoffee as TbCoffeeIcon,
  TbCoin,
  TbCompass as TbCompassIcon,
  TbCreditCard as TbCreditCardIcon,
  TbFish as TbFishIcon,
  TbFlame as TbFlameIcon,
  TbGift as TbGiftIcon,
  TbGlassFull,
  TbHeart as TbHeartIcon,
  TbHelp,
  TbHome as TbHomeIcon,
  TbIceCream as TbIceCreamIcon,
  TbInfoCircle,
  TbLink as TbLinkIcon,
  TbMail as TbMailIcon,
  TbMapPin as TbMapPinIcon,
  TbMessageCircle as TbMessageCircleIcon,
  TbMusic as TbMusicIcon,
  TbNavigation as TbNavigationIcon,
  TbPackage as TbPackageIcon,
  TbPercentage,
  TbPhone as TbPhoneIcon,
  TbPizza as TbPizzaIcon,
  TbQrcode as TbQrcodeIcon,
  TbReceipt as TbReceiptIcon,
  TbShare as TbShareIcon,
  TbShieldCheck as TbShieldCheckIcon,
  TbShoppingBag as TbShoppingBagIcon,
  TbShoppingCart as TbShoppingCartIcon,
  TbSparkles as TbSparklesIcon,
  TbStar as TbStarIcon,
  TbTag as TbTagIcon,
  TbThumbUp,
  TbTicket as TbTicketIcon,
  TbToolsKitchen2,
  TbTruckDelivery,
  TbUser as TbUserIcon,
  TbUsers as TbUsersIcon,
  TbVideo as TbVideoIcon,
  TbWorld,
} from "react-icons/tb";

// Ionicons
import {
  IoBagOutline,
  IoBedOutline,
  IoBeerOutline,
  IoBookOutline,
  IoBookmarkOutline,
  IoBusinessOutline,
  IoCafeOutline,
  IoCalendarOutline,
  IoCallOutline,
  IoCameraOutline,
  IoCarOutline,
  IoCardOutline,
  IoCartOutline,
  IoCashOutline,
  IoChatbubbleOutline,
  IoColorPaletteOutline,
  IoCompassOutline,
  IoCutOutline,
  IoFastFoodOutline,
  IoFishOutline,
  IoFitnessOutline,
  IoFlameOutline,
  IoFlashOutline,
  IoGiftOutline,
  IoGlassesOutline,
  IoGlobeOutline,
  IoHeartOutline,
  IoHelpCircleOutline,
  IoHomeOutline,
  IoIceCreamOutline,
  IoInformationCircleOutline,
  IoLinkOutline,
  IoLocationOutline,
  IoLogoDiscord,
  IoLogoFacebook,
  IoLogoGoogle,
  IoLogoInstagram,
  IoLogoLinkedin,
  IoLogoPinterest,
  IoLogoSnapchat,
  IoLogoTiktok,
  IoLogoTwitter,
  IoLogoWhatsapp,
  IoLogoYoutube,
  IoMailOutline,
  IoMusicalNotesOutline,
  IoNavigateOutline,
  IoNotificationsOutline,
  IoPawOutline,
  IoPeopleOutline,
  IoPersonOutline,
  IoPizzaOutline,
  IoPricetagOutline,
  IoPricetagsOutline,
  IoQrCodeOutline,
  IoReceiptOutline,
  IoRestaurantOutline,
  IoShareSocialOutline,
  IoShieldCheckmarkOutline,
  IoShirtOutline,
  IoSparklesOutline,
  IoStarOutline,
  IoStorefrontOutline,
  IoThumbsUpOutline,
  IoTicketOutline,
  IoTimeOutline,
  IoVideocamOutline,
  IoWineOutline,
} from "react-icons/io5";

// Phosphor
import {
  PiBag,
  PiBeerBottle,
  PiBell as PiBellIcon,
  PiBookOpen as PiBookOpenIcon,
  PiBookmark as PiBookmarkIcon,
  PiBuildings,
  PiCake as PiCakeIcon,
  PiCalendar as PiCalendarIcon,
  PiCamera as PiCameraIcon,
  PiChatCircleDots,
  PiClock as PiClockIcon,
  PiCoffee as PiCoffeeIcon,
  PiCoins as PiCoinsIcon,
  PiCompass as PiCompassIcon,
  PiCreditCard as PiCreditCardIcon,
  PiDiscordLogo,
  PiEnvelopeSimple,
  PiFacebookLogo,
  PiFire as PiFireIcon,
  PiFish as PiFishIcon,
  PiForkKnife,
  PiGift as PiGiftIcon,
  PiGlobe as PiGlobeIcon,
  PiGoogleLogo,
  PiHamburger,
  PiHeart as PiHeartIcon,
  PiHouse as PiHouseIcon,
  PiIceCream as PiIceCreamIcon,
  PiInfo as PiInfoIcon,
  PiInstagramLogo,
  PiLightning,
  PiLink as PiLinkIcon,
  PiLinkedinLogo,
  PiMapPin as PiMapPinIcon,
  PiMusicNotes,
  PiNavigationArrow,
  PiPackage as PiPackageIcon,
  PiPercent as PiPercentIcon,
  PiPhone as PiPhoneIcon,
  PiPinterestLogo,
  PiPizza as PiPizzaIcon,
  PiQrCode as PiQrCodeIcon,
  PiQuestion,
  PiReceipt as PiReceiptIcon,
  PiShareNetwork,
  PiShieldCheck as PiShieldCheckIcon,
  PiShoppingCart as PiShoppingCartIcon,
  PiSnapchatLogo,
  PiSparkle,
  PiSpotifyLogo,
  PiStar as PiStarIcon,
  PiStorefront,
  PiTag as PiTagIcon,
  PiTelegramLogo,
  PiThumbsUp as PiThumbsUpIcon,
  PiTicket as PiTicketIcon,
  PiTiktokLogo,
  PiTruck as PiTruckIcon,
  PiUser as PiUserIcon,
  PiUsers as PiUsersIcon,
  PiVideoCamera,
  PiWhatsappLogo,
  PiWine as PiWineIcon,
  PiXLogo,
  PiYoutubeLogo,
} from "react-icons/pi";

import type { ScanMeLinksIconPackage } from "@/lib/scanme-links-design";
import { cn } from "@/lib/utils";
import styles from "./template-icon.module.css";

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

const brandIcons: Record<string, SimpleIcon> = {
  facebook: siFacebook,
  instagram: siInstagram,
  telegram: siTelegram,
  tiktok: siTiktok,
  viber: siViber,
  whatsapp: siWhatsapp,
  youtube: siYoutube,
};

const genericIcons: Record<string, LucideIcon> = {
  calendar: CalendarDays,
  globe: Globe2,
  link: LinkIcon,
  linkedin: Contact,
  mail: Mail,
  "map-pin": MapPin,
  phone: Phone,
  store: Store,
  "shopping-bag": ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  menu: Menu,
  ticket: Ticket,
  truck: Truck,
  percent: Percent,
  gift: Gift,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  clock: Clock,
  music: Music,
  camera: Camera,
  "message-circle": MessageCircle,
  navigation: Navigation,
  tag: Tag,
  "credit-card": CreditCard,
  "book-open": BookOpen,
  user: User,
  home: Home,
  "qr-code": QrCode,
};

const LIBRARY_ICON_COMPONENTS: Record<string, IconComponent> = {
  // Lucide
  "lu:instagram": LuInstagram,
  "lu:facebook": LuFacebook,
  "lu:youtube": LuYoutube,
  "lu:twitter": LuTwitter,
  "lu:linkedin": LuLinkedin,
  "lu:github": LuGithub,
  "lu:phone": LuPhone,
  "lu:mail": LuMail,
  "lu:map-pin": LuMapPin,
  "lu:navigation": LuNavigation,
  "lu:globe": LuGlobe,
  "lu:calendar": LuCalendar,
  "lu:clock": LuClock,
  "lu:message-circle": LuMessageCircle,
  "lu:user": LuUser,
  "lu:users": LuUsers,
  "lu:building": LuBuilding,
  "lu:info": LuInfo,
  "lu:utensils": LuUtensils,
  "lu:coffee": LuCoffee,
  "lu:wine": LuWine,
  "lu:beer": LuBeer,
  "lu:pizza": LuPizza,
  "lu:cup-soda": LuCupSoda,
  "lu:cake": LuCake,
  "lu:chef-hat": LuChefHat,
  "lu:croissant": LuCroissant,
  "lu:salad": LuSalad,
  "lu:soup": LuSoup,
  "lu:cookie": LuCookie,
  "lu:ice-cream-bowl": LuIceCreamBowl,
  "lu:shopping-bag": LuShoppingBag,
  "lu:shopping-cart": LuShoppingCart,
  "lu:store": LuStore,
  "lu:tag": LuTag,
  "lu:percent": LuPercent,
  "lu:gift": LuGift,
  "lu:credit-card": LuCreditCard,
  "lu:ticket": LuTicket,
  "lu:truck": LuTruck,
  "lu:receipt": LuReceipt,
  "lu:banknote": LuBanknote,
  "lu:package": LuPackage,
  "lu:star": LuStar,
  "lu:heart": LuHeart,
  "lu:sparkles": LuSparkles,
  "lu:music": LuMusic,
  "lu:camera": LuCamera,
  "lu:video": LuVideo,
  "lu:link": LuLink,
  "lu:qr-code": LuQrCode,
  "lu:house": LuHouse,
  "lu:bell": LuBell,
  "lu:shield-check": LuShieldCheck,
  "lu:flame": LuFlame,
  "lu:zap": LuZap,
  "lu:compass": LuCompass,
  "lu:bookmark": LuBookmark,
  "lu:share-2": LuShare2,
  "lu:thumbs-up": LuThumbsUp,
  "lu:circle-help": LuCircleHelp,

  // Font Awesome 6
  "fa6:FaInstagram": FaInstagram6,
  "fa6:FaFacebookF": FaFacebookF,
  "fa6:FaTiktok": FaTiktok6,
  "fa6:FaYoutube": FaYoutube6,
  "fa6:FaWhatsapp": FaWhatsapp6,
  "fa6:FaViber": FaViber6,
  "fa6:FaTelegram": FaTelegram6,
  "fa6:FaLinkedinIn": FaLinkedinIn,
  "fa6:FaXTwitter": FaXTwitter,
  "fa6:FaSpotify": FaSpotify,
  "fa6:FaPinterestP": FaPinterestP,
  "fa6:FaGoogle": FaGoogle,
  "fa6:FaYelp": FaYelp,
  "fa6:FaDiscord": FaDiscord,
  "fa6:FaSnapchat": FaSnapchat,
  "fa6:FaPhone": FaPhone6,
  "fa6:FaEnvelope": FaEnvelope,
  "fa6:FaLocationDot": FaLocationDot,
  "fa6:FaLocationArrow": FaLocationArrow,
  "fa6:FaGlobe": FaGlobe6,
  "fa6:FaCalendarDays": FaCalendarDays6,
  "fa6:FaClock": FaClock6,
  "fa6:FaCommentDots": FaCommentDots,
  "fa6:FaUser": FaUser6,
  "fa6:FaUsers": FaUsers6,
  "fa6:FaBuilding": FaBuilding6,
  "fa6:FaCircleInfo": FaCircleInfo,
  "fa6:FaUtensils": FaUtensils6,
  "fa6:FaMugHot": FaMugHot,
  "fa6:FaWineGlass": FaWineGlass,
  "fa6:FaBeerMugEmpty": FaBeerMugEmpty,
  "fa6:FaPizzaSlice": FaPizzaSlice,
  "fa6:FaBurger": FaBurger,
  "fa6:FaCakeCandles": FaCakeCandles,
  "fa6:FaBookOpen": FaBookOpen,
  "fa6:FaIceCream": FaIceCream6,
  "fa6:FaFish": FaFish,
  "fa6:FaFire": FaFire,
  "fa6:FaBagShopping": FaBagShopping,
  "fa6:FaCartShopping": FaCartShopping,
  "fa6:FaShop": FaShop,
  "fa6:FaTag": FaTag6,
  "fa6:FaPercent": FaPercent6,
  "fa6:FaGift": FaGift6,
  "fa6:FaCreditCard": FaCreditCard6,
  "fa6:FaTicket": FaTicket6,
  "fa6:FaTruck": FaTruck6,
  "fa6:FaReceipt": FaReceipt6,
  "fa6:FaCoins": FaCoins,
  "fa6:FaBoxOpen": FaBoxOpen,
  "fa6:FaStar": FaStar6,
  "fa6:FaHeart": FaHeart6,
  "fa6:FaWandMagicSparkles": FaWandMagicSparkles,
  "fa6:FaMusic": FaMusic6,
  "fa6:FaCamera": FaCamera6,
  "fa6:FaVideo": FaVideo6,
  "fa6:FaLink": FaLink6,
  "fa6:FaQrcode": FaQrcode6,
  "fa6:FaHouse": FaHouse6,
  "fa6:FaBell": FaBell,
  "fa6:FaShieldHalved": FaShieldHalved,
  "fa6:FaBolt": FaBolt,
  "fa6:FaCompass": FaCompass6,
  "fa6:FaBookmark": FaBookmark,
  "fa6:FaShareNodes": FaShareNodes,
  "fa6:FaThumbsUp": FaThumbsUp6,
  "fa6:FaCircleQuestion": FaCircleQuestion,

  // Tabler
  "tb:TbBrandInstagram": TbBrandInstagram,
  "tb:TbBrandFacebook": TbBrandFacebook,
  "tb:TbBrandTiktok": TbBrandTiktok,
  "tb:TbBrandYoutube": TbBrandYoutube,
  "tb:TbBrandWhatsapp": TbBrandWhatsapp,
  "tb:TbBrandTelegram": TbBrandTelegram,
  "tb:TbBrandLinkedin": TbBrandLinkedin,
  "tb:TbBrandX": TbBrandX,
  "tb:TbBrandSpotify": TbBrandSpotify,
  "tb:TbBrandPinterest": TbBrandPinterest,
  "tb:TbBrandGoogle": TbBrandGoogle,
  "tb:TbBrandTripadvisor": TbBrandTripadvisor,
  "tb:TbBrandDiscord": TbBrandDiscord,
  "tb:TbBrandSnapchat": TbBrandSnapchat,
  "tb:TbPhone": TbPhoneIcon,
  "tb:TbMail": TbMailIcon,
  "tb:TbMapPin": TbMapPinIcon,
  "tb:TbNavigation": TbNavigationIcon,
  "tb:TbWorld": TbWorld,
  "tb:TbCalendar": TbCalendarIcon,
  "tb:TbClock": TbClockIcon,
  "tb:TbMessageCircle": TbMessageCircleIcon,
  "tb:TbUser": TbUserIcon,
  "tb:TbUsers": TbUsersIcon,
  "tb:TbBuilding": TbBuildingIcon,
  "tb:TbInfoCircle": TbInfoCircle,
  "tb:TbToolsKitchen2": TbToolsKitchen2,
  "tb:TbCoffee": TbCoffeeIcon,
  "tb:TbGlassFull": TbGlassFull,
  "tb:TbBeer": TbBeer,
  "tb:TbPizza": TbPizzaIcon,
  "tb:TbBurger": TbBurgerIcon,
  "tb:TbCake": TbCakeIcon,
  "tb:TbBook": TbBookIcon,
  "tb:TbIceCream": TbIceCreamIcon,
  "tb:TbFish": TbFishIcon,
  "tb:TbFlame": TbFlameIcon,
  "tb:TbShoppingBag": TbShoppingBagIcon,
  "tb:TbShoppingCart": TbShoppingCartIcon,
  "tb:TbBuildingStore": TbBuildingStore,
  "tb:TbTag": TbTagIcon,
  "tb:TbPercentage": TbPercentage,
  "tb:TbGift": TbGiftIcon,
  "tb:TbCreditCard": TbCreditCardIcon,
  "tb:TbTicket": TbTicketIcon,
  "tb:TbTruckDelivery": TbTruckDelivery,
  "tb:TbReceipt": TbReceiptIcon,
  "tb:TbCoin": TbCoin,
  "tb:TbPackage": TbPackageIcon,
  "tb:TbStar": TbStarIcon,
  "tb:TbHeart": TbHeartIcon,
  "tb:TbSparkles": TbSparklesIcon,
  "tb:TbMusic": TbMusicIcon,
  "tb:TbCamera": TbCameraIcon,
  "tb:TbVideo": TbVideoIcon,
  "tb:TbLink": TbLinkIcon,
  "tb:TbQrcode": TbQrcodeIcon,
  "tb:TbHome": TbHomeIcon,
  "tb:TbBell": TbBellIcon,
  "tb:TbShieldCheck": TbShieldCheckIcon,
  "tb:TbBolt": TbBoltIcon,
  "tb:TbCompass": TbCompassIcon,
  "tb:TbBookmark": TbBookmarkIcon,
  "tb:TbShare": TbShareIcon,
  "tb:TbThumbUp": TbThumbUp,
  "tb:TbHelp": TbHelp,

  // Ionicons
  "io5:IoLogoInstagram": IoLogoInstagram,
  "io5:IoLogoFacebook": IoLogoFacebook,
  "io5:IoLogoTiktok": IoLogoTiktok,
  "io5:IoLogoYoutube": IoLogoYoutube,
  "io5:IoLogoWhatsapp": IoLogoWhatsapp,
  "io5:IoLogoTwitter": IoLogoTwitter,
  "io5:IoLogoLinkedin": IoLogoLinkedin,
  "io5:IoLogoGoogle": IoLogoGoogle,
  "io5:IoLogoPinterest": IoLogoPinterest,
  "io5:IoLogoDiscord": IoLogoDiscord,
  "io5:IoLogoSnapchat": IoLogoSnapchat,
  "io5:IoCallOutline": IoCallOutline,
  "io5:IoMailOutline": IoMailOutline,
  "io5:IoLocationOutline": IoLocationOutline,
  "io5:IoNavigateOutline": IoNavigateOutline,
  "io5:IoGlobeOutline": IoGlobeOutline,
  "io5:IoCalendarOutline": IoCalendarOutline,
  "io5:IoTimeOutline": IoTimeOutline,
  "io5:IoChatbubbleOutline": IoChatbubbleOutline,
  "io5:IoPersonOutline": IoPersonOutline,
  "io5:IoPeopleOutline": IoPeopleOutline,
  "io5:IoBusinessOutline": IoBusinessOutline,
  "io5:IoInformationCircleOutline": IoInformationCircleOutline,
  "io5:IoRestaurantOutline": IoRestaurantOutline,
  "io5:IoCafeOutline": IoCafeOutline,
  "io5:IoWineOutline": IoWineOutline,
  "io5:IoBeerOutline": IoBeerOutline,
  "io5:IoPizzaOutline": IoPizzaOutline,
  "io5:IoFastFoodOutline": IoFastFoodOutline,
  "io5:IoIceCreamOutline": IoIceCreamOutline,
  "io5:IoFishOutline": IoFishOutline,
  "io5:IoFlameOutline": IoFlameOutline,
  "io5:IoBookOutline": IoBookOutline,
  "io5:IoBagOutline": IoBagOutline,
  "io5:IoCartOutline": IoCartOutline,
  "io5:IoStorefrontOutline": IoStorefrontOutline,
  "io5:IoPricetagOutline": IoPricetagOutline,
  "io5:IoPricetagsOutline": IoPricetagsOutline,
  "io5:IoGiftOutline": IoGiftOutline,
  "io5:IoCardOutline": IoCardOutline,
  "io5:IoTicketOutline": IoTicketOutline,
  "io5:IoReceiptOutline": IoReceiptOutline,
  "io5:IoCashOutline": IoCashOutline,
  "io5:IoCutOutline": IoCutOutline,
  "io5:IoFitnessOutline": IoFitnessOutline,
  "io5:IoCarOutline": IoCarOutline,
  "io5:IoBedOutline": IoBedOutline,
  "io5:IoPawOutline": IoPawOutline,
  "io5:IoShirtOutline": IoShirtOutline,
  "io5:IoColorPaletteOutline": IoColorPaletteOutline,
  "io5:IoStarOutline": IoStarOutline,
  "io5:IoHeartOutline": IoHeartOutline,
  "io5:IoSparklesOutline": IoSparklesOutline,
  "io5:IoGlassesOutline": IoGlassesOutline,
  "io5:IoMusicalNotesOutline": IoMusicalNotesOutline,
  "io5:IoCameraOutline": IoCameraOutline,
  "io5:IoVideocamOutline": IoVideocamOutline,
  "io5:IoLinkOutline": IoLinkOutline,
  "io5:IoQrCodeOutline": IoQrCodeOutline,
  "io5:IoHomeOutline": IoHomeOutline,
  "io5:IoNotificationsOutline": IoNotificationsOutline,
  "io5:IoShieldCheckmarkOutline": IoShieldCheckmarkOutline,
  "io5:IoFlashOutline": IoFlashOutline,
  "io5:IoCompassOutline": IoCompassOutline,
  "io5:IoBookmarkOutline": IoBookmarkOutline,
  "io5:IoShareSocialOutline": IoShareSocialOutline,
  "io5:IoThumbsUpOutline": IoThumbsUpOutline,
  "io5:IoHelpCircleOutline": IoHelpCircleOutline,

  // Phosphor
  "pi:PiInstagramLogo": PiInstagramLogo,
  "pi:PiFacebookLogo": PiFacebookLogo,
  "pi:PiTiktokLogo": PiTiktokLogo,
  "pi:PiYoutubeLogo": PiYoutubeLogo,
  "pi:PiWhatsappLogo": PiWhatsappLogo,
  "pi:PiTelegramLogo": PiTelegramLogo,
  "pi:PiLinkedinLogo": PiLinkedinLogo,
  "pi:PiXLogo": PiXLogo,
  "pi:PiSpotifyLogo": PiSpotifyLogo,
  "pi:PiPinterestLogo": PiPinterestLogo,
  "pi:PiGoogleLogo": PiGoogleLogo,
  "pi:PiDiscordLogo": PiDiscordLogo,
  "pi:PiSnapchatLogo": PiSnapchatLogo,
  "pi:PiPhone": PiPhoneIcon,
  "pi:PiEnvelopeSimple": PiEnvelopeSimple,
  "pi:PiMapPin": PiMapPinIcon,
  "pi:PiNavigationArrow": PiNavigationArrow,
  "pi:PiGlobe": PiGlobeIcon,
  "pi:PiCalendar": PiCalendarIcon,
  "pi:PiClock": PiClockIcon,
  "pi:PiChatCircleDots": PiChatCircleDots,
  "pi:PiUser": PiUserIcon,
  "pi:PiUsers": PiUsersIcon,
  "pi:PiBuildings": PiBuildings,
  "pi:PiInfo": PiInfoIcon,
  "pi:PiForkKnife": PiForkKnife,
  "pi:PiCoffee": PiCoffeeIcon,
  "pi:PiWine": PiWineIcon,
  "pi:PiBeerBottle": PiBeerBottle,
  "pi:PiPizza": PiPizzaIcon,
  "pi:PiHamburger": PiHamburger,
  "pi:PiCake": PiCakeIcon,
  "pi:PiBookOpen": PiBookOpenIcon,
  "pi:PiIceCream": PiIceCreamIcon,
  "pi:PiFish": PiFishIcon,
  "pi:PiFire": PiFireIcon,
  "pi:PiBag": PiBag,
  "pi:PiShoppingCart": PiShoppingCartIcon,
  "pi:PiStorefront": PiStorefront,
  "pi:PiTag": PiTagIcon,
  "pi:PiPercent": PiPercentIcon,
  "pi:PiGift": PiGiftIcon,
  "pi:PiCreditCard": PiCreditCardIcon,
  "pi:PiTicket": PiTicketIcon,
  "pi:PiTruck": PiTruckIcon,
  "pi:PiReceipt": PiReceiptIcon,
  "pi:PiCoins": PiCoinsIcon,
  "pi:PiPackage": PiPackageIcon,
  "pi:PiStar": PiStarIcon,
  "pi:PiHeart": PiHeartIcon,
  "pi:PiSparkle": PiSparkle,
  "pi:PiMusicNotes": PiMusicNotes,
  "pi:PiCamera": PiCameraIcon,
  "pi:PiVideoCamera": PiVideoCamera,
  "pi:PiLink": PiLinkIcon,
  "pi:PiQrCode": PiQrCodeIcon,
  "pi:PiHouse": PiHouseIcon,
  "pi:PiBell": PiBellIcon,
  "pi:PiShieldCheck": PiShieldCheckIcon,
  "pi:PiLightning": PiLightning,
  "pi:PiCompass": PiCompassIcon,
  "pi:PiBookmark": PiBookmarkIcon,
  "pi:PiShareNetwork": PiShareNetwork,
  "pi:PiThumbsUp": PiThumbsUpIcon,
  "pi:PiQuestion": PiQuestion,
};

const PACKAGE_CLASS: Record<ScanMeLinksIconPackage, string> = {
  line: styles.line,
  solid: styles.solid,
  "soft-3d": styles.soft3d,
};

export function TemplateIcon({
  iconKey,
  className,
  packageStyle = "line",
}: {
  iconKey: string;
  className?: string;
  packageStyle?: ScanMeLinksIconPackage;
}) {
  const treatment = cn(styles.glyph, PACKAGE_CLASS[packageStyle]);

  // 1. Check if it's one of the 5 library prefixed icons
  const LibraryIcon = LIBRARY_ICON_COMPONENTS[iconKey];
  if (LibraryIcon) {
    const isSolidLibrary = iconKey.startsWith("fa6:");
    return (
      <LibraryIcon
        aria-hidden="true"
        className={cn(
          className,
          treatment,
          !isSolidLibrary && styles.generic,
        )}
      />
    );
  }

  // 2. Check legacy simple-icons brand
  const brand = brandIcons[iconKey];
  if (brand) {
    return (
      <svg
        viewBox="0 0 24 24"
        role="img"
        aria-hidden="true"
        className={cn(className, treatment)}
        fill="currentColor"
      >
        <path d={brand.path} />
      </svg>
    );
  }

  // 3. Check legacy generic icons
  const Icon = genericIcons[iconKey] ?? LinkIcon;
  return (
    <Icon
      aria-hidden="true"
      className={cn(className, treatment, styles.generic)}
    />
  );
}
