import {
  SCANME_LINKS_PRESET_KEYS,
  type ScanMeLinksBackgroundV2,
  type ScanMeLinksColorsV2,
  type ScanMeLinksDesignV2,
  type ScanMeLinksPresetKey,
} from "./scanme-links-design";

/**
 * A variation is a named colour/background swap inside a preset. It carries no
 * layout of its own: every variation of a preset renders the exact same markup
 * and the same CSS classes, and only moves the custom-property values the
 * template already reads.
 */
export type ScanMeLinksVariation = {
  key: string;
  label: string;
  colors: ScanMeLinksColorsV2;
  background: ScanMeLinksBackgroundV2;
  /** Only set when the variation intentionally departs from the preset default. */
  typography?: Partial<
    Pick<ScanMeLinksDesignV2["typography"], "fontKey" | "headingWeight">
  >;
  buttons?: Partial<Pick<ScanMeLinksDesignV2["buttons"], "variant">>;
  /** Three-stop preview used by the editor's variation cards. */
  swatch: readonly [string, string, string];
};

const NUDE_EDITORIAL: readonly ScanMeLinksVariation[] = [
  {
    key: "nude-editorial-1",
    label: "Ivory",
    swatch: ["#F6F0E8", "#FFFFFF", "#B99A80"],
    background: { category: "flat", color: "#F6F0E8" },
    colors: {
      page: "#F6F0E8",
      surface: "#FFFFFF",
      title: "#2E2823",
      body: "#6B615A",
      accent: "#B99A80",
      border: "#E7DACC",
      focus: "#8C7357",
      button: "#FFFFFF",
      buttonHover: "#FBF6F0",
      buttonText: "#2E2823",
      icon: "#4A4038",
    },
  },
  {
    key: "nude-editorial-2",
    label: "Sage",
    swatch: ["#829690", "#FFFFFF", "#35403D"],
    background: { category: "flat", color: "#829690" },
    colors: {
      page: "#829690",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      // Matches the reference, where title and subtitle share one white.
      body: "#FFFFFF",
      accent: "#FFFFFF",
      border: "#FFFFFF",
      focus: "#FFFFFF",
      button: "#FFFFFF",
      buttonHover: "#F4F8F7",
      buttonText: "#35403D",
      icon: "#4C5A56",
    },
  },
  {
    key: "nude-editorial-3",
    label: "Paper",
    swatch: ["#FFFFFF", "#ECECEC", "#1A1A1A"],
    background: { category: "flat", color: "#FFFFFF" },
    colors: {
      page: "#FFFFFF",
      surface: "#F2F2F2",
      title: "#111111",
      body: "#55555A",
      accent: "#9B9B9B",
      border: "#DEDEDE",
      focus: "#6E6E6E",
      button: "#ECECEC",
      buttonHover: "#E3E3E3",
      buttonText: "#1A1A1A",
      icon: "#1A1A1A",
    },
  },
  {
    key: "nude-editorial-4",
    label: "Camel",
    swatch: ["#DDB98C", "#6B4A2F", "#F6EADA"],
    background: { category: "flat", color: "#DDB98C" },
    colors: {
      page: "#DDB98C",
      surface: "#EFD6B6",
      title: "#3A2A1C",
      body: "#5A4433",
      accent: "#6B4A2F",
      border: "#B98F63",
      focus: "#4A3220",
      button: "#6B4A2F",
      buttonHover: "#5C3F27",
      buttonText: "#F6EADA",
      icon: "#F6EADA",
    },
  },
];

const URBAN_POP: readonly ScanMeLinksVariation[] = [
  {
    key: "urban-pop-1",
    label: "Blaze",
    swatch: ["#F02D1E", "#FBA61C", "#111111"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#F02D1E",
      endColor: "#FBA61C",
      angle: 168,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#F02D1E",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#FFE6DC",
      accent: "#111111",
      border: "#111111",
      focus: "#111111",
      button: "#FFFFFF",
      buttonHover: "#F1F1F1",
      buttonText: "#111111",
      icon: "#111111",
    },
  },
  {
    key: "urban-pop-2",
    label: "Neon",
    swatch: ["#A02BF5", "#3FE0C8", "#111111"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#A02BF5",
      endColor: "#3FE0C8",
      angle: 162,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#A02BF5",
      surface: "#FFFFFF",
      title: "#34E7CF",
      body: "#FFFFFF",
      accent: "#111111",
      border: "#111111",
      focus: "#111111",
      button: "#FFFFFF",
      buttonHover: "#F1F1F1",
      buttonText: "#111111",
      icon: "#111111",
    },
  },
  {
    key: "urban-pop-3",
    label: "Midnight",
    swatch: ["#2B302E", "#B4F03C", "#FFFFFF"],
    background: { category: "flat", color: "#2B302E" },
    colors: {
      page: "#2B302E",
      surface: "#FFFFFF",
      title: "#B4F03C",
      body: "#D6D9D4",
      accent: "#111111",
      border: "#111111",
      focus: "#B4F03C",
      button: "#FFFFFF",
      buttonHover: "#F1F1F1",
      buttonText: "#111111",
      icon: "#111111",
    },
  },
  {
    key: "urban-pop-4",
    label: "Comic",
    swatch: ["#FFC91F", "#F5A300", "#111111"],
    background: {
      category: "pattern",
      variant: "dots",
      backgroundColor: "#FFC91F",
      patternColor: "#F0A000",
      scale: 16,
      opacity: 0.55,
    },
    colors: {
      page: "#FFC91F",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#4A3800",
      accent: "#111111",
      border: "#111111",
      focus: "#111111",
      button: "#FFFFFF",
      buttonHover: "#F1F1F1",
      buttonText: "#111111",
      icon: "#111111",
    },
  },
];

const ARTISAN_CRAFT: readonly ScanMeLinksVariation[] = [
  {
    key: "artisan-craft-1",
    label: "Aged Paper",
    swatch: ["#EFE0C4", "#A87C52", "#6B3F1D"],
    background: {
      category: "texture",
      variant: "paper",
      backgroundColor: "#EFE0C4",
      tintColor: "#AE8B58",
      intensity: 0.8,
    },
    colors: {
      page: "#EFE0C4",
      surface: "#F7EEDD",
      title: "#6B3F1D",
      body: "#7A5C3E",
      accent: "#8A5A3B",
      border: "#C9A87C",
      focus: "#6B4325",
      button: "#90663C",
      buttonHover: "#7F562F",
      buttonText: "#FBF3E6",
      icon: "#FBF3E6",
    },
  },
  {
    key: "artisan-craft-2",
    label: "Navy Plaster",
    swatch: ["#24374F", "#A87C52", "#F3E7D2"],
    background: {
      category: "texture",
      variant: "linen",
      backgroundColor: "#24374F",
      tintColor: "#4A6484",
      intensity: 0.5,
    },
    colors: {
      page: "#24374F",
      surface: "#33496380",
      title: "#F3E7D2",
      body: "#D3C3A6",
      accent: "#C9A87C",
      border: "#8A6B49",
      focus: "#E0C79C",
      button: "#90663C",
      buttonHover: "#7F562F",
      buttonText: "#FBF3E6",
      icon: "#FBF3E6",
    },
  },
  {
    key: "artisan-craft-3",
    label: "Cream",
    swatch: ["#F5E6C8", "#8A5A3B", "#6B3F1D"],
    background: { category: "flat", color: "#F5E6C8" },
    colors: {
      page: "#F5E6C8",
      surface: "#FBF3E1",
      title: "#6B3F1D",
      body: "#7A5C3E",
      accent: "#8A5A3B",
      border: "#C9A87C",
      focus: "#6B4325",
      button: "#8A5A3B",
      buttonHover: "#794E32",
      buttonText: "#FBF3E6",
      icon: "#FBF3E6",
    },
  },
  {
    key: "artisan-craft-4",
    label: "Dark Wood",
    swatch: ["#2E1E13", "#8A2E22", "#E8D5A9"],
    background: {
      category: "texture",
      variant: "wood",
      backgroundColor: "#2E1E13",
      tintColor: "#6B4A2E",
      intensity: 0.9,
    },
    colors: {
      page: "#2E1E13",
      surface: "#43301F",
      title: "#E8D5A9",
      body: "#C0A47A",
      accent: "#C9A87C",
      border: "#6B4A2E",
      focus: "#E0C79C",
      button: "#8A2E22",
      buttonHover: "#77281D",
      buttonText: "#F6E3C8",
      icon: "#F6E3C8",
    },
  },
];

const GLASS_MINIMALIST: readonly ScanMeLinksVariation[] = [
  {
    key: "glass-minimalist-1",
    label: "Deep Teal",
    swatch: ["#1E6B72", "#0A1E2A", "#FFFFFF"],
    background: {
      category: "gradient",
      variant: "radial",
      startColor: "#1E6B72",
      endColor: "#0A1E2A",
      angle: 135,
      centerX: 42,
      centerY: 34,
    },
    colors: {
      page: "#0A1E2A",
      surface: "#2E6F78",
      title: "#FFFFFF",
      body: "#CFE3E6",
      accent: "#7FB6C4",
      border: "#FFFFFF",
      focus: "#9FD3E0",
      button: "#FFFFFF",
      buttonHover: "#FFFFFF",
      buttonText: "#FFFFFF",
      icon: "#FFFFFF",
    },
  },
  {
    key: "glass-minimalist-2",
    label: "Slate",
    swatch: ["#5B7486", "#1E2428", "#DCEBF5"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#5B7486",
      endColor: "#1E2428",
      angle: 168,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#1E2428",
      surface: "#596B76",
      title: "#DCEBF5",
      body: "#C0CFD8",
      accent: "#9BB6C6",
      border: "#FFFFFF",
      focus: "#CFE2ED",
      button: "#FFFFFF",
      buttonHover: "#FFFFFF",
      buttonText: "#FFFFFF",
      icon: "#FFFFFF",
    },
  },
  {
    key: "glass-minimalist-3",
    label: "Blanc",
    swatch: ["#FFFFFF", "#F2F2F2", "#111111"],
    background: { category: "flat", color: "#FFFFFF" },
    colors: {
      page: "#FFFFFF",
      surface: "#F0F0F0",
      title: "#111111",
      body: "#4A4A4A",
      accent: "#8A8A8A",
      border: "#E0E0E0",
      focus: "#6E6E6E",
      button: "#FFFFFF",
      buttonHover: "#FFFFFF",
      buttonText: "#1A1A1A",
      icon: "#111111",
    },
  },
  {
    key: "glass-minimalist-4",
    label: "Gold",
    swatch: ["#A46F00", "#6B4A12", "#FFF6E0"],
    // The reference sets this variation in a serif; the others stay geometric.
    typography: { fontKey: "cormorant-garamond" },
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#A46F00",
      endColor: "#6B4A12",
      angle: 152,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#6B4A12",
      surface: "#8A6420",
      title: "#FFF6E0",
      body: "#EAD8AC",
      accent: "#E8C46A",
      border: "#FFFFFF",
      focus: "#F2DCA6",
      button: "#FFFFFF",
      buttonHover: "#FFFFFF",
      buttonText: "#FFF6E0",
      icon: "#FFF6E0",
    },
  },
];

const WANDERLUST: readonly ScanMeLinksVariation[] = [
  {
    key: "wanderlust-1",
    label: "Aurora Teal",
    swatch: ["#070D12", "#4ED8C7", "#FFFFFF"],
    background: {
      category: "media",
      mediaType: "image",
      fit: "cover",
      zoom: 1,
      positionX: 50,
      positionY: 50,
      overlayColor: "#070D12",
      overlayOpacity: 0.1,
    },
    colors: {
      page: "#070D12",
      surface: "#10222B",
      title: "#FFFFFF",
      body: "#4ED8C7",
      accent: "#4ED8C7",
      border: "#38C9B8",
      focus: "#4ED8C7",
      button: "rgba(14, 26, 33, 0.65)",
      buttonHover: "rgba(22, 38, 48, 0.78)",
      buttonText: "#FFFFFF",
      icon: "#14968B",
    },
  },
  {
    key: "wanderlust-2",
    label: "Northern Violet",
    swatch: ["#0B0714", "#C084FC", "#FFFFFF"],
    background: {
      category: "animation",
      variant: "aurora",
      baseColor: "#0B0714",
      accentColor: "#A855F7",
      speed: 1,
      intensity: 0.5,
    },
    colors: {
      page: "#0B0714",
      surface: "#1F132B",
      title: "#FFFFFF",
      body: "#D8B4FE",
      accent: "#C084FC",
      border: "#A855F7",
      focus: "#C084FC",
      button: "rgba(26, 16, 40, 0.65)",
      buttonHover: "rgba(38, 24, 59, 0.78)",
      buttonText: "#FFFFFF",
      icon: "#9333EA",
    },
  },
  {
    key: "wanderlust-3",
    label: "Emerald Night",
    swatch: ["#05120B", "#34D399", "#FFFFFF"],
    background: {
      category: "animation",
      variant: "aurora",
      baseColor: "#05120B",
      accentColor: "#10B981",
      speed: 1,
      intensity: 0.5,
    },
    colors: {
      page: "#05120B",
      surface: "#0D2418",
      title: "#FFFFFF",
      body: "#6EE7B7",
      accent: "#34D399",
      border: "#10B981",
      focus: "#34D399",
      button: "rgba(11, 30, 20, 0.65)",
      buttonHover: "rgba(18, 46, 32, 0.78)",
      buttonText: "#FFFFFF",
      icon: "#059669",
    },
  },
  {
    key: "wanderlust-4",
    label: "Cyber Cyan",
    swatch: ["#040B14", "#00F0FF", "#FFFFFF"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#040B14",
      endColor: "#082032",
      angle: 175,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#040B14",
      surface: "#0A1E30",
      title: "#FFFFFF",
      body: "#38BDF8",
      accent: "#00F0FF",
      border: "#00D2E0",
      focus: "#00F0FF",
      button: "rgba(8, 27, 43, 0.65)",
      buttonHover: "rgba(14, 40, 63, 0.78)",
      buttonText: "#FFFFFF",
      icon: "#0284C7",
    },
  },
];

const BISTRO: readonly ScanMeLinksVariation[] = [
  {
    key: "bistro-1",
    label: "Rust & Bronze",
    swatch: ["#140A06", "#522216", "#E0B27E"],
    background: {
      category: "media",
      mediaType: "image",
      fit: "cover",
      zoom: 1,
      positionX: 50,
      positionY: 50,
      overlayColor: "#000000",
      overlayOpacity: 0.25,
    },
    colors: {
      page: "#140A06",
      surface: "#522216",
      title: "#F7E6D0",
      body: "#D4B18C",
      accent: "#E0B27E",
      border: "#C48D5E",
      focus: "#E0B27E",
      button: "#522216",
      buttonHover: "#662C1E",
      buttonText: "#FFFFFF",
      icon: "#E0B27E",
    },
  },
  {
    key: "bistro-2",
    label: "Dark Espresso",
    swatch: ["#0D0B0A", "#261E1A", "#D4AF37"],
    background: {
      category: "texture",
      variant: "wood",
      backgroundColor: "#0D0B0A",
      tintColor: "#261E1A",
      intensity: 0.6,
    },
    colors: {
      page: "#0D0B0A",
      surface: "#261E1A",
      title: "#FFF8ED",
      body: "#D9C9B4",
      accent: "#D4AF37",
      border: "#B8972E",
      focus: "#D4AF37",
      button: "#261E1A",
      buttonHover: "#382D27",
      buttonText: "#FFFFFF",
      icon: "#D4AF37",
    },
  },
  {
    key: "bistro-3",
    label: "Forest Tavern",
    swatch: ["#0A120D", "#1C3325", "#E5C28A"],
    background: {
      category: "texture",
      variant: "wood",
      backgroundColor: "#0A120D",
      tintColor: "#1C3325",
      intensity: 0.6,
    },
    colors: {
      page: "#0A120D",
      surface: "#1C3325",
      title: "#F4EBD9",
      body: "#B8CEBF",
      accent: "#E5C28A",
      border: "#A68650",
      focus: "#E5C28A",
      button: "#1C3325",
      buttonHover: "#284A36",
      buttonText: "#FFFFFF",
      icon: "#E5C28A",
    },
  },
  {
    key: "bistro-4",
    label: "Vintage Wine",
    swatch: ["#14070A", "#3D131D", "#E8BE92"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#14070A",
      endColor: "#240B11",
      angle: 160,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#14070A",
      surface: "#3D131D",
      title: "#FDF2E7",
      body: "#D8B4B8",
      accent: "#E8BE92",
      border: "#B38259",
      focus: "#E8BE92",
      button: "#3D131D",
      buttonHover: "#521B28",
      buttonText: "#FFFFFF",
      icon: "#E8BE92",
    },
  },
];

const BLOOM: readonly ScanMeLinksVariation[] = [
  {
    key: "bloom-1",
    label: "Peach Sunset",
    swatch: ["#E6D3DF", "#FFFFFF", "#2D2430"],
    background: {
      category: "media",
      mediaType: "image",
      fit: "cover",
      zoom: 1,
      positionX: 50,
      positionY: 50,
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    colors: {
      page: "#E6D3DF",
      surface: "#FFFFFF",
      title: "#2D2430",
      body: "#6E6172",
      accent: "#B65E7D",
      border: "#F0E4EC",
      focus: "#B65E7D",
      button: "#FFFFFF",
      buttonHover: "#FAF5F8",
      buttonText: "#2D2430",
      icon: "#B65E7D",
    },
  },
  {
    key: "bloom-2",
    label: "Lavender Cloud",
    swatch: ["#E0DEF4", "#FFFFFF", "#2B243B"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#E0DEF4",
      endColor: "#F4E8EE",
      angle: 145,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#E0DEF4",
      surface: "#FFFFFF",
      title: "#2B243B",
      body: "#6A6380",
      accent: "#8B6FBA",
      border: "#ECE8F5",
      focus: "#8B6FBA",
      button: "#FFFFFF",
      buttonHover: "#F6F4FA",
      buttonText: "#2B243B",
      icon: "#8B6FBA",
    },
  },
  {
    key: "bloom-3",
    label: "Rose Garden",
    swatch: ["#FCE4EC", "#FFFFFF", "#3E2229"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#FCE4EC",
      endColor: "#FFF3E0",
      angle: 135,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#FCE4EC",
      surface: "#FFFFFF",
      title: "#3E2229",
      body: "#78535C",
      accent: "#C25975",
      border: "#F8E1E7",
      focus: "#C25975",
      button: "#FFFFFF",
      buttonHover: "#FDF4F6",
      buttonText: "#3E2229",
      icon: "#C25975",
    },
  },
  {
    key: "bloom-4",
    label: "Mint Blossom",
    swatch: ["#D8F3DC", "#FFFFFF", "#1B3B2B"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#D8F3DC",
      endColor: "#FFF0F5",
      angle: 155,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#D8F3DC",
      surface: "#FFFFFF",
      title: "#1B3B2B",
      body: "#486B58",
      accent: "#40916C",
      border: "#D0EED5",
      focus: "#40916C",
      button: "#FFFFFF",
      buttonHover: "#F2FBF5",
      buttonText: "#1B3B2B",
      icon: "#40916C",
    },
  },
];

const CHICKEN: readonly ScanMeLinksVariation[] = [
  {
    key: "chicken-1",
    label: "Pop Sunburst",
    swatch: ["#F6C928", "#FFFFFF", "#000000"],
    background: {
      category: "media",
      mediaType: "image",
      fit: "cover",
      zoom: 1,
      positionX: 50,
      positionY: 50,
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    colors: {
      page: "#F6C928",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#000000",
      accent: "#298BE8",
      border: "#000000",
      focus: "#298BE8",
      button: "#FFFFFF",
      buttonHover: "#F7F7F7",
      buttonText: "#000000",
      icon: "#000000",
    },
  },
  {
    key: "chicken-2",
    label: "Electric Orange",
    swatch: ["#FF6B35", "#FFFFFF", "#000000"],
    background: {
      category: "pattern",
      variant: "dots",
      backgroundColor: "#FF6B35",
      patternColor: "#E04810",
      scale: 20,
      opacity: 0.3,
    },
    colors: {
      page: "#FF6B35",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#000000",
      accent: "#00E5FF",
      border: "#000000",
      focus: "#00E5FF",
      button: "#FFFFFF",
      buttonHover: "#F7F7F7",
      buttonText: "#000000",
      icon: "#000000",
    },
  },
  {
    key: "chicken-3",
    label: "Cherry Comic",
    swatch: ["#E63946", "#FFFFFF", "#000000"],
    background: {
      category: "pattern",
      variant: "checker",
      backgroundColor: "#E63946",
      patternColor: "#C1121F",
      scale: 24,
      opacity: 0.25,
    },
    colors: {
      page: "#E63946",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#000000",
      accent: "#FFD166",
      border: "#000000",
      focus: "#FFD166",
      button: "#FFFFFF",
      buttonHover: "#F7F7F7",
      buttonText: "#000000",
      icon: "#000000",
    },
  },
  {
    key: "chicken-4",
    label: "Neon Lime",
    swatch: ["#A7F432", "#FFFFFF", "#000000"],
    background: {
      category: "pattern",
      variant: "waves",
      backgroundColor: "#A7F432",
      patternColor: "#84D014",
      scale: 22,
      opacity: 0.3,
    },
    colors: {
      page: "#A7F432",
      surface: "#FFFFFF",
      title: "#FFFFFF",
      body: "#000000",
      accent: "#7B2CBF",
      border: "#000000",
      focus: "#7B2CBF",
      button: "#FFFFFF",
      buttonHover: "#F7F7F7",
      buttonText: "#000000",
      icon: "#000000",
    },
  },
];

const PULSE: readonly ScanMeLinksVariation[] = [
  {
    key: "pulse-1",
    label: "Cyber Pulse",
    swatch: ["#070A0F", "#00F0FF", "#E040FB"],
    background: {
      category: "media",
      mediaType: "image",
      fit: "cover",
      zoom: 1,
      positionX: 50,
      positionY: 50,
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    colors: {
      page: "#070A0F",
      surface: "#101622",
      title: "#FFFFFF",
      body: "#E040FB",
      accent: "#00F0FF",
      border: "#00F0FF",
      focus: "#00F0FF",
      button: "rgba(16, 22, 34, 0.85)",
      buttonHover: "rgba(24, 33, 50, 0.95)",
      buttonText: "#FFFFFF",
      icon: "#00F0FF",
    },
  },
  {
    key: "pulse-2",
    label: "Electric Violet",
    swatch: ["#0A0612", "#A855F7", "#38BDF8"],
    background: {
      category: "animation",
      variant: "aurora",
      baseColor: "#0A0612",
      accentColor: "#A855F7",
      speed: 1.2,
      intensity: 0.6,
    },
    colors: {
      page: "#0A0612",
      surface: "#181028",
      title: "#FFFFFF",
      body: "#38BDF8",
      accent: "#C084FC",
      border: "#A855F7",
      focus: "#C084FC",
      button: "rgba(24, 16, 40, 0.85)",
      buttonHover: "rgba(36, 24, 60, 0.95)",
      buttonText: "#FFFFFF",
      icon: "#C084FC",
    },
  },
  {
    key: "pulse-3",
    label: "Matrix Emerald",
    swatch: ["#040D08", "#00FF88", "#00E5FF"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#040D08",
      endColor: "#0A1F14",
      angle: 170,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#040D08",
      surface: "#0B2115",
      title: "#FFFFFF",
      body: "#00E5FF",
      accent: "#00FF88",
      border: "#00E575",
      focus: "#00FF88",
      button: "rgba(11, 33, 21, 0.85)",
      buttonHover: "rgba(16, 48, 30, 0.95)",
      buttonText: "#FFFFFF",
      icon: "#00FF88",
    },
  },
  {
    key: "pulse-4",
    label: "Solar Flare",
    swatch: ["#0F0606", "#FF3366", "#FFB703"],
    background: {
      category: "gradient",
      variant: "linear",
      startColor: "#0F0606",
      endColor: "#220C0C",
      angle: 160,
      centerX: 50,
      centerY: 50,
    },
    colors: {
      page: "#0F0606",
      surface: "#241010",
      title: "#FFFFFF",
      body: "#FFB703",
      accent: "#FF3366",
      border: "#FF2A55",
      focus: "#FF3366",
      button: "rgba(36, 16, 16, 0.85)",
      buttonHover: "rgba(52, 24, 24, 0.95)",
      buttonText: "#FFFFFF",
      icon: "#FF3366",
    },
  },
];

export const SCANME_LINKS_VARIATIONS: Record<
  ScanMeLinksPresetKey,
  readonly ScanMeLinksVariation[]
> = {
  gentle: [],
  ios: [],
  lux: [],
  rustic: [],
  minimal: [],
  bold: [],
  "nude-editorial": NUDE_EDITORIAL,
  "urban-pop": URBAN_POP,
  "artisan-craft": ARTISAN_CRAFT,
  "glass-minimalist": GLASS_MINIMALIST,
  wanderlust: WANDERLUST,
  bistro: BISTRO,
  bloom: BLOOM,
  chicken: CHICKEN,
  pulse: PULSE,
};

export function variationsForPreset(presetKey: ScanMeLinksPresetKey) {
  return SCANME_LINKS_VARIATIONS[presetKey];
}

export function findVariation(
  presetKey: ScanMeLinksPresetKey,
  variationKey: string | undefined,
): ScanMeLinksVariation | null {
  if (!variationKey) return null;
  return (
    SCANME_LINKS_VARIATIONS[presetKey].find(
      (variation) => variation.key === variationKey,
    ) ?? null
  );
}

/**
 * Returns `design` with the variation's tokens applied. Everything the
 * variation does not name — button geometry, spacing, shadows, alignment —
 * is left exactly as the caller had it, so a user who tuned the radius keeps
 * that radius when switching colours.
 */
export function applyVariation(
  design: ScanMeLinksDesignV2,
  variation: ScanMeLinksVariation,
): ScanMeLinksDesignV2 {
  return {
    ...design,
    variationKey: variation.key,
    colors: { ...variation.colors },
    background: { ...variation.background },
    buttons: { ...design.buttons, ...variation.buttons },
    typography: { ...design.typography, ...variation.typography },
  };
}

export const ALL_VARIATION_KEYS = SCANME_LINKS_PRESET_KEYS.flatMap((presetKey) =>
  SCANME_LINKS_VARIATIONS[presetKey].map((variation) => variation.key),
);
